name: 'apt-key-add'
description: 'Add a new key to the list of trusted keys.'
inputs:
  key-url:
    description: 'Key URL.'
  key-fingerprint:
    description: 'Expected key fingerprint.'
runs:
  using: 'node16'
  main: 'dist/index.js'
